### PR TITLE
made the site responsive for mobile screens(550px)

### PR DESCRIPTION
**Pull request by Awesomeasma**
screencapture-file-C-Users-ASMA-NAAZ-real-time-file-share-public-home-html-2023-03-08-12_21_55
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #(issue without the braces)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by Awesomeasma** [comment]
It's done, sir, Please review it

**Comment by firtysh** [comment]
> It's done, sir, Please review it

the screenshot you provided is the end result?

**Comment by Awesomeasma** [comment]
> > It's done, sir, Please review it
> 
> the screenshot you provided is the end result?

Yes

**Comment by firtysh** [comment]
> > > It's done, sir, Please review it
> > 
> > 
> > the screenshot you provided is the end result?
> 
> Yes

Soory but this isn't enough you should have used hamburger menu for the navbar and the fonts are still not responsive

**Pull request closed without merging**
