### PR TITLE
Just added midnight blue color

### LINKED ISSUE #4: text visibility fix.
Screenshot from 2023-02-12 23-01-39
Make the texts here more visible

### PR DESCRIPTION
**Pull request by mecivil**
Only added color .Don't know if it's sufficient.

### CODE REVIEW

**Comment by firtysh** [comment]
> Only added color .Don't know if it's sufficient.

Please add a screenshot of the change and mention the issue no.

**Comment by mecivil** [comment]
image  
I did make the text prominent as you required and made the pull request.   
Issue#4

**Comment by firtysh** [comment]
> image I did make the text prominent as you required and made the pull request. Issue#4

this doesn't fix the issue for smaller devices try adding some media queries

**Comment by mecivil** [comment]
image
Please confirm whether it will work like this.

**Comment by firtysh** [comment]
> image Please confirm whether it will work like this.

How did you replicated the issue did you follow all the instruction mentioned in README.md. There should be a room id too but in your screenshots the room id is blank

**Comment by firtysh** [comment]
> image Please confirm whether it will work like this.

How did you replicated the issue did you follow all the instruction mentioned in README.md. There should be a room id too but in your screenshots the room id is blank

**Comment by mecivil** [comment]
image  
I added media queries as well as added the room id as it remained missing when  I ran it locally.
Please comment on whether the improvements are sufficient .

**Comment by mecivil** [comment]
image
It looks like this in small screens

**Comment by firtysh** [comment]
> image It looks like this in small screens

Push your final changes

**Pull request closed without merging**
