### PR TITLE
Added click to copy functionality.

### LINKED ISSUE #3: Add click to copy feature for room id
Screenshot from 2023-02-12 22-54-09
implement a feature to copy the room id on click.

### PR DESCRIPTION
**Pull request by RishabhJain0721**
I have added a demo room id in the sender.html .Clicking on the room id will copy it.

### CODE REVIEW

**Comment by firtysh** [comment]
> I have added a demo room id in the sender.html .Clicking on the room id will copy it.

Do not add extra demo room id implement the feature on the room id generated by websocket.
Add a screenshot of the change and mention the issue no.

**Comment by RishabhJain0721** [comment]
Alright @firtysh

**Comment by RishabhJain0721** [comment]
Issue no. 3 

[Untitled_ Feb 15, 2023 2_28 AM.webm](https://user-images.githubusercontent.com/107767172/218862199-c365f6b4-375b-48e4-a1e5-c5f0efe754b6.webm)

**Comment by RishabhJain0721** [comment]
Hi @firtysh I have done the stuff you asked

**Comment by firtysh** [comment]
> Hi @firtysh I have done the stuff you asked

You don't need to add demo id 

> Hi @firtysh I have done the stuff you asked

Cool.
Next time you make a pr keep these things in mind:
record or take screenshot after making the final changes.
mention the issue no with the hashtag like #3

**Comment by firtysh** [comment]
@RishabhJain0721  Sorry I closed the pr by mistake but you will get your point.

**Comment by RishabhJain0721** [comment]
Alright 

> > Hi @firtysh I have done the stuff you asked
> 
> You don't need to add demo id
> 
> > Hi @firtysh I have done the stuff you asked
> 
> Cool. Next time you make a pr keep these things in mind: record or take screenshot after making the final changes. mention the issue no with the hashtag like #3

Alright @firtysh I'll keep that in mind

**Comment by RishabhJain0721** [comment]
> @RishabhJain0721 Sorry I closed the pr by mistake but you will get your point.

Thank you

**Pull request merged**
