### PR TITLE
Added Landing Page 

### LINKED ISSUE #2: create landing page
Create a landing page for "/" endpoint.

### PR DESCRIPTION
**Pull request by adityakhattri21**
Added Landing page under Issue #2 at ('/') route with redirection to send or receive route.  
Screenshot 2023-02-15 111047
Screenshot 2023-02-15 111034
Screenshot 2023-02-15 111013

Added few instructions . 
Screenshot 2023-02-15 130359

### CODE REVIEW

**Comment by firtysh** [comment]
> I have added a landing page which is accessible at home('/') route. From there it can be redirected to send or receive route.

Please add a screenshot and mention the issue no.

**Comment by adityakhattri21** [comment]
> > I have added a landing page which is accessible at home('/') route. From there it can be redirected to send or receive route.
> 
> Please add a screenshot and mention the issue . 
 I have updated my comment . Please look and merge the request or suggest any changes.

**Comment by firtysh** [comment]
> > > I have added a landing page which is accessible at home('/') route. From there it can be redirected to send or receive route.
> > 
> > 
> > Please add a screenshot and mention the issue .
> > I have updated my comment . Please look and merge the request or suggest any changes.
Nice. If you could just add some text in the page which explains the features of the webapp it would be better. A landing page can't just have two buttons right

**Comment by adityakhattri21** [comment]
> > > > I have added a landing page which is accessible at home('/') route. From there it can be redirected to send or receive route.
> > > 
> > > 
> > > Please add a screenshot and mention the issue .
> > > I have updated my comment . Please look and merge the request or suggest any changes.
> > > Nice. If you could just add some text in the page which explains the features of the webapp it would be better. A landing page can't just have two buttons right

I have made changes . Please look into it and let me know

**Pull request merged**
